name: Build IconSvg Plugin

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          # 安装基础工具
          brew install perl make git
          
          # 使用官方推荐方式安装Theos
          git clone --depth=1 https://github.com/theos/theos.git ~/theos
          echo "export THEOS=~/theos" >> ~/.zshrc
          echo "export PATH=$THEOS/bin:$PATH" >> ~/.zshrc
          source ~/.zshrc

      - name: Install ldid
        run: |
          curl -LO https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_macosx_arm64
          chmod +x ldid_macosx_arm64
          sudo mv ldid_macosx_arm64 /usr/local/bin/ldid

      - name: Build Plugin
        run: |
          export THEOS=~/theos
          export PATH=$THEOS/bin:$PATH
          export SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)
          
          # 验证环境
          $THEOS/bin/nic.pl list
          make --version
          
          # 开始编译
          make package FINALPACKAGE=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: IconSvg-Plugin
          path: packages/*.deb
